### ISSUE TITLE
Could not find queueit_knownuserv3-3.5.0 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by wonderwoman13** [queueit/KnownUser.V3.RubyOnRails#3]
Just a quick note that by yanking down version 3.5.0, we had a Staging deploy fail. Luckily, we caught it before we deployed to Production. A friendly note to remember that yanking a gem can be dangerous. 

Users that have the yanked version in their Gemfile.lock will suddenly get errors the next time they deploy. Depending on how your deploy process is setup, this could cause downtime.

Thank you for all of your great work on this gem!

**Comment by frwiqueueit** [comment]
Thank you, Brittany.

You are right that it's dangerous, but in a way the effect you describe is also what we wanted. 
We knew that version v.3.5 for ruby was broken, so having it running in production would be bad.

I really appreciate that you reached out and told us this. I hope we will not be yanking more gems in the future :)

**Comment by frwiqueueit** [comment]
I'm closing this one. Anybody using v.3.5 should downgrade to v.3.4.
v.3.5.1 will be out soon.

**Comment by wonderwoman13** [comment]
As a note, I was mistaken. We did deploy this to Production and it just caused us to fail out on our on-sale. If you yank a gem version again, we need to be notified, please.

**Comment by frwiqueueit** [comment]
I'm very sorry to hear that. Next time we will definitively inform you in due time.
One thing that troubles me is that another customer of ours informed us that version 3.5 was broken (would not run) and we could verify this. So how you managed to get it working in your staging and later production environments is a mystery to me.

**Comment by wonderwoman13** [comment]
@frwiqueueit there is a simple answer to that: we deployed 3.5 and did not have an on sale until today. The dependency got locked into the Gemfile.lock when you released it and then we didn't use it until today.
